version: '3.8'

services:
  # Servicio Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backoffice-backend
    restart: unless-stopped
    ports:
      - "3013:3000"
    volumes:
      - ./backend/data:/app/data
    environment:
      - NODE_ENV=production
      - PORT=3000
    networks:
      - backoffice-network

  # Servicio Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=http://backend:3000/api
    container_name: backoffice-frontend
    restart: unless-stopped
    ports:
      - "3014:80"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://backend:3000/api
    networks:
      - backoffice-network

networks:
  backoffice-network:
    driver: bridge
